
# // -----------------------------add Accessoire ---------------------
# POST http://localhost:3900/psapi/accessoires
# content-type: application/json

# {
#     "name": "ANGULAIRE PASSANT",
#     "image": "images/accessoires/angulairePassant.jpg"
# }

// -----------------------------add categorie service ---------------------

# POST http://localhost:3900/psapi/categoriesvc
# content-type: application/json

# {
#     "name": "Ligne de vie horizontale",
#     "smallDesc":"Ligne de vie horizontale au MAROC Etude et installation de la ligne de vie horizontale au MAROC chez P&S ",
#     "largeDesc": "La ligne de vie horizontale est un dispositif constitué d’au moins deux points d’ancrage entre lesquels un câble, une corde, une sangle ou une chaîne, appelé support d’assurage, est tendue. L’utilisateur s’attache directement à ce support d’assurage souple ou rigide. Grâce à nos lignes de vie",
#     "image":"images/accessoires/ligneVieHorizon.jpg"
# }

// -----------------------------add service ---------------------

POST http://localhost:3900/psapi/services
content-type: application/json

{

    "name": "lignes de vie sur bac",
    "caracteristiques":["Bac acier partir de 0,5","Certifiées selon EN 795-C  pour 2 utilisateurs"],
    "images":["image1","image2","image3"] ,
    "accessoires":["5fe755771a214ccdb68144c0","5fe757721a214ccdb68144c1"],
    "categorie":"5fe7818c1d936a73778504f3"

}
