
// -----------------------------add Accessoire ---------------------
POST http://localhost:3900/psapi/accessoires
content-type: application/json

{
    "name": "ANGULAIRE PASSANT",
    "image": "images/accessoires/angulairePassant.jpg"
}

// -----------------------------add categorie service ---------------------

# POST http://localhost:3900/psapi/categoriesvc
# content-type: application/json

# {
#     "name": "Ligne de vie horizontale",
#     "smallDesc":"Ligne de vie horizontale au MAROC Etude et installation de la ligne de vie horizontale au MAROC chez P&S ",
#     "largeDesc": "La ligne de vie horizontale est un dispositif constitué d’au moins deux points d’ancrage entre lesquels un câble, une corde, une sangle ou une chaîne, appelé support d’assurage, est tendue. L’utilisateur s’attache directement à ce support d’assurage souple ou rigide. Grâce à nos lignes de vie",
#     "image":"images/accessoires/ligneVieHorizon.jpg"
# }

// -----------------------------add service ---------------------

# POST http://localhost:3900/psapi/services
# content-type: application/json

# {

#     "name": "lignes de vie sur bac",
#     "caracteristiques":["Bac acier partir de 0,5","Certifiées selon EN 795-C  pour 2 utilisateurs"],
#     "images":["image1","image2","image3"] ,
#     "accessoires":["5fe755771a214ccdb68144c0","5fe757721a214ccdb68144c1"],
#     "categorie":"5fe7818c1d936a73778504f3"

# }


// -----------------------------add categorie produit ---------------------

# POST http://localhost:3900/psapi/productscategorie
# content-type: application/json

# {
#     "name": "equipement de protection individuel",
#     "description":"equipement de protection individuel au MAROC Etude et installation de la ligne de vie horizontale au MAROC chez P&S ",
#     "image":"images/categorieProduit/equipementProtection.jpg"
# }



// -----------------------------add categorie produit ---------------------

# POST http://localhost:3900/psapi/productstype
# content-type: application/json

# {
#     "name": "harnais",
#     "image":"images/productType/harnais.jpg",
#     "description":"equipements de protection  individuel",
#     "categorie":"5ff0bdc047a96b3c4c6be7a1"
# }



# # // -----------------------------add client ---------------------
# POST http://localhost:3900/psapi/clients
# content-type: application/json

# {
#     "name": "mourad",
#     "email":"mouradvilla2@gmail.com"
# }
// -----------------------------add product ---------------------
POST http://localhost:3900/psapi/products
content-type: application/json

{
    "name": "GAIA",
    "image":"",
    "type":"5ff0bdf647a96b3c4c6be7a2",
    "description":"Le harnais de travail GAIA pour positionnement et suspension est simple à enfiler et polyvalent."

 }
# # // -----------------------------add post ---------------------

# PUT http://localhost:3900/psapi/products/avis/5feb86589cccef541d042638
# content-type: application/json

# {
#     "note": 4,
#     "comment":"tres bon produit",
#     "client": {
#         "name":"nouraddin",
#         "email":"mouradvilla3@gmail.com"
#     }
    
# }
        
   
# // -----------------------------add command ---------------------

# PUT http://localhost:3900/psapi/products/commands/5fea22c9a6141795169992c7
# content-type: application/json

# {
#     "numberArticle": 3,
#     "message":"je pourais prendre plus",
#     "client": {
#         "name":"hamid",
#         "email":"mouradvilla@gmail.com"
#     }
    
# }
        