//---------------------------- mofidy military man---------------

PUT http://localhost:3900/ct/militaires/5fe0eadd0c18264551a80aab
content-type: application/json

{
  "nom": "fathii",
  "prenom": "nouraddin",
  "grade": "1°cl",
  "mle": "945/222234",
  "uniteOrigine": "44°BIS",
  "fonction": "5fe0ea1e0c18264551a80aa6"
}